---
log_level: warn

# PostgreSQL connection configuration
postgres:
  host: localhost:5544
  user: testkit
  password: badger
  database: testkit_db
  query_params:
    sslmode: disable

# Elasticsearch connection configuration
elasticsearch:
  addresses: http://localhost:9211 # comma separated list of addresses
  username: testkit
  password: badger

opensearch:
  addresses: http://localhost:9202 # comma separated list of addresses
  username: admin
  password: admin

api-mock:
  address: http://localhost:8181