---
log_level: trace

# PostgreSQL connection configuration
postgres:
  host: localhost:5544
  user: testkit
  password: badger
  database: testkit_db
  query_params:
    sslmode: disable

# Elasticsearch connection configuration
elasticsearch:
  addresses: http://localhost:9200 # comma separated list of addresses
  username: testkit
  password: badger
