---
log_level: trace

# PostgreSQL connection configuration
postgres:
  host: localhost:5544
  user: testkit
  password: badger
  database: testkit_db
  query_params:
    sslmode: disable

# MySQL connection configuration
kafka:
  host: localhost:9092
  topic: testkit
  group_id: testkit
  auto_offset_reset: earliest