---
services:
  postgres:
    image: postgres:14.2
    container_name: testkit-postgres
    ports:
      - '5544:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: testkit_db
      POSTGRES_USER: testkit
      POSTGRES_PASSWORD: badger
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d testkit_db -U testkit" ]
      interval: 5s
      timeout: 60s
      retries: 10