---
services:
  postgres:
    image: postgres:14.2
    container_name: testkit-postgres
    ports:
      - '5544:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: testkit_db
      POSTGRES_USER: testkit
      POSTGRES_PASSWORD: badger
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d testkit_db -U testkit" ]
      interval: 5s
      timeout: 10s
      retries: 30

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: testkit-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: testkit
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      discovery.type: single-node
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 120

  opensearch:
    container_name: testkit-os
    image: opensearchproject/opensearch:2.7.0
    ports:
      - "9202:9202"
    environment: # USER: admin PASSWORD: admin
      - "discovery.type=single-node"
      - "plugins.security.ssl.http.enabled=false"
      - "http.port=9202"

  api_mock:
    container_name: testkit-api-mock
    image: wiremock/wiremock:latest
    ports:
      - "8181:8080"