name: "Base branch: Checks"

on:
  push:
    branches:
      - master
      - main

jobs:
  go-lint:
    name: "GoLang Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          go-version-file: go.mod
          
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Start containers
        run: docker compose -f .github/assets/docker-compose.yml up -d

      - name: Install dependencies
        run: make deps

      - name: Wait for containers to start
        run: .github/assets/wait.sh

      - name: Run tests
        run: make tests