name: "PR: Checks"

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Start containers
        run: docker compose -f .github/assets/docker-compose.yml up -d

      - name: Install dependencies
        run: go get . && go install gotest.tools/gotestsum@latest

      - name: Run tests
        run: gotestsum --format testname